version: '3.8'

services:
  frontend:
    container_name: bulletin-board-dev
    image: bulletin-board-image-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
